### ISSUE TITLE
shredstream-proxy  udp data analysis

### ISSUE THREAD

**Issue by GXKe** [jito-labs/shredstream-proxy#23]
I want to implement a program to parse the Shreds data received by the proxy, while avoiding running the complete Solana node. Has anyone in the community done this feature for reference?

**Comment by aMagicNeko** [comment]
Hi, brother, I want this too. How's it going with you

**Comment by GXKe** [comment]
Just started, ready to modify node code to receive and parse transaction data

**Comment by GXKe** [comment]
The function has been completed,  It's easier than expected

**Comment by skypro1111** [comment]
> The function has been completed, It's easier than expected

hi, can you provide some info about "how to" ?

**Comment by uetkaje** [comment]
> The function has been completed, It's easier than expected

Hey @GXKe 

I'm struggling same objective. But I'm not able to deshred transaction data by using [deshred function](https://github.com/solana-labs/solana/blob/master/ledger/src/shredder.rs#L394)
Could you please share an example?

Thanks in advance.

Best regards,
Emre
