### ISSUE TITLE
No received any data

### ISSUE THREAD

**Issue by undefinedteam1** [jito-labs/shredstream-proxy#27]
Hi, 

Me started ShredStream Proxy and set dest-ip-ports to localhost:8080 and my websocket server listening on port 8080
But on my server, not received any data.
Can you help me fix this.
Thanks

**Comment by esemeniuc** [comment]
Shreds are UDP packets, not websocket. This will not work for websocket listeners. You need to point it to your RPC instance

**Comment by undefinedteam1** [comment]
> Shreds are UDP packets, not websocket. This will not work for websocket listeners. You need to point it to your RPC instance

I'm not running a RPC Node, I just want listen newest transaction. Can you tell me what I need do ?

Thanks

**Comment by esemeniuc** [comment]
You can get all transactions with https://solana.com/docs/rpc/websocket/blocksubscribe

**Comment by undefinedteam1** [comment]
But its normal method are delay 2 sec. I find some method to received tx at 'processed' level  is using shredStream or using validator with geyser plugin
I tried install validator with non voting, but its required high CPU and RAM (Someone tell me using fresh Node, but idk)
Other method are using shredStream
Can you suggest me right method?

Thanks

**Comment by esemeniuc** [comment]
i don't have a method personally. you can try asking on solana discord
